[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# regex = "0.1.41"
reg = { git = "https://github.com/rust-lang/regex.git", package = "regex" }
tokio = { version = "1", features = ["full"] }
