[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# regex = "0.1.41"
tiny_http = "0.6.2"
serde_json = "1.0.64"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = [
    "blocking",
], default-features = false }
