@hostname = api.example.com
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
###
# @name google
# @name baidu
@baidub = hello
GET https://baidu.com HTTP/1.1
###
POST http://127.0.0.1:3000  HTTP/1.1

{{baidub}}

###
# @prompt username
# @prompt refCode Your reference code display on webpage
# @prompt otp Your one-time password in your mailbox
# @name verify
POST https://{{host}}/verify-otp/{{refCode}} HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "{{username}}",
    "otp": "{{otp}}"
}
