openapi: "3.0.3"
info:
  title: APTS OpenAPI
  version: "1.0.0"
servers:
  - url: https://10.166.209.110
paths:
  /opapi/wsm/v1/apts/healthcheck:
    post:
      summary: Create health check task
      description: Creates a health check task for the specified object and configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                object:
                  type: string
                  description: The object to perform the health check on.
                  example: cluster
                checkSubInfo:
                  type: object
                  properties:
                    gpuConsistencyCheck:
                      type: array
                      items:
                        type: string
                      example: ["gpuharddropnum"]
                    rdmaConsistencyCheck:
                      type: array
                      items:
                        type: string
                      example: ["rdmaportnum"]
                healthCheckCfg:
                  type: object
                  properties:
                    rdmaNums:
                      type: integer
                      example: 10
                    gpuNums:
                      type: integer
                      example: 10
      responses:
        "201":
          description: Health check task created successfully.
    get:
      summary: Get health check result
      description: Retrieves the result of a health check task.
      responses:
        "200":
          description: Successful response with health check result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        object:
                          type: string
                          example: cluster
                        checkType:
                          type: string
                          example: gpuAvailability
                        checkSubItem:
                          type: string
                          example: gpustatus
                        subResult:
                          type: string
                          example: healthy
                        checkDetail:
                          type: string
                          example: "检查通过: 共检查 5 个节点， 40 个GPU。\n"
                        status:
                          type: string
                          example: completed
                        startTime:
                          type: string
                          format: date-time
                          example: "2025-01-14T14:07:39+08:00"
                        endTime:
                          type: string
                          format: date-time
                          example: "2025-01-14T14:07:39+08:00"
                  status:
                    type: string
                    example: completed
  /opapi/wsm/v1/apts/gpuinspectiontask:
    post:
      summary: Create GPU inspection task
      description: Creates a GPU inspection task with specified configurations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                diag_configs:
                  type: array
                  items:
                    type: object
                    properties:
                      vendor:
                        type: string
                      diag_param:
                        type: string
                      diag_level:
                        type: string
                inspect_count:
                  type: integer
                inspect_type:
                  type: string
      responses:
        "201":
          description: GPU inspection task created successfully.
    delete:
      summary: Delete GPU inspection task
      description: Deletes the specified GPU inspection task.
      responses:
        "204":
          description: Task deleted successfully.
    get:
      summary: Get GPU inspection result
      description: Retrieves the result of a GPU inspection task.
      responses:
        "200":
          description: Successful response with GPU inspection results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  diag_created:
                    type: string
                    format: date-time
                  diag_gpu_outputs:
                    type: array
                    items:
                      type: object
                      properties:
                        diag_exec_errmsg:
                          type: string
                        gpuUUID:
                          type: string
                        result:
                          type: string
                        vendor:
                          type: string
  /opapi/wsm/v1/apts/scclinspection/start:
    post:
      summary: Create SCCL inspection task
      description: Creates an SCCL inspection task with specified parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inspectType:
                  type: string
                  example: BRCCL
                cclType:
                  type: string
                  example: AllReduce
                command:
                  type: string
                  example: "-G 1 -b 512 -e 20m"
                gpuPerNode:
                  type: integer
                  example: 8
                nodeList:
                  type: array
                  items:
                    type: string
                  example: ["cluster-cim2-minion-0-1"]
                testScene:
                  type: string
                  example: cluster
                outAlgbw:
                  type: number
                  example: 0
                outBusbw:
                  type: number
                  example: 0
                inAlgbw:
                  type: number
                  example: 0
                inBusbw:
                  type: number
                  example: 0
      responses:
        "201":
          description: SCCL inspection task created successfully.
  /opapi/wsm/v1/apts/scclinspection/stop:
    post:
      summary: Delete SCCL inspection task
      description: Stops the SCCL inspection task.
      responses:
        "204":
          description: Task stopped successfully.
  /opapi/wsm/v1/apts/scclinspection/query:
    get:
      summary: Get SCCL inspection result
      description: Retrieves the result of an SCCL inspection task.
      responses:
        "200":
          description: Successful response with SCCL inspection results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  scclResult:
                    type: object
                    properties:
                      data:
                        type: object
                        description: Additional data for SCCL result.
                      result:
                        type: object
                        properties:
                          passNodeNum:
                            type: integer
                            example: 0
                          failNodeNum:
                            type: integer
                            example: 0
                          failNodeList:
                            type: array
                            items:
                              type: string
                            example: null
                  gpuNum:
                    type: integer
                    example: 8
                  nodeNum:
                    type: integer
                    example: 1
                  status:
                    type: string
                    example: finished
                  cclType:
                    type: string
                    example: AllReduce
                  testScene:
                    type: string
                    example: cluster
                  result:
                    type: string
                    example: pass
                  inAlgbw:
                    type: number
                    example: 37.7
                  inBusbw:
                    type: number
                    example: 65.98
                  outAlgbw:
                    type: number
                    example: 25.34
                  outBusbw:
                    type: number
                    example: 44.34
  /opapi/wsm/v1/apts/rdma/submit:
    post:
      summary: "Create RDMA Inspection Task"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                testScene:
                  type: string
                  example: "singleNode"
                bandWidthThreshold:
                  type: number
                  example: 0
                nodeList:
                  type: array
                  items:
                    type: string
                  example: ["cluster-cim2-minion-0-1"]
      responses:
        "200":
          description: "RDMA inspection task created successfully."
  /opapi/wsm/v1/apts/rdma/stop:
    post:
      summary: "Delete RDMA Inspection Task"
      responses:
        "200":
          description: "RDMA inspection task deleted successfully."
  /opapi/wsm/v1/apts/rdma/querybandwidth:
    get:
      summary: "Get RDMA Inspection Result"
      responses:
        "200":
          description: "RDMA inspection results retrieved successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  testRdmaResultList:
                    type: array
                    items:
                      type: object
                      properties:
                        localNodeName:
                          type: string
                          example: "cluster-cim2-minion-0-1"
                        localRdmaInterface:
                          type: string
                          example: "mlx5_12"
                        localNetDev:
                          type: string
                          example: "ens5f0"
                        localPci:
                          type: string
                          example: "0000:9d:00.0"
                        localLinkSpeed:
                          type: string
                          example: "200 Gb/s"
                        remoteNodeName:
                          type: string
                          example: "cluster-cim2-minion-0-1"
                        remoteRdmaInterface:
                          type: string
                          example: "mlx5_4"
                        remoteNetDev:
                          type: string
                          example: "ens1f0"
                        remotePci:
                          type: string
                          example: "0000:1b:00.0"
                        remoteLinkSpeed:
                          type: string
                          example: "200 Gb/s"
                        testResult:
                          type: string
                          example: "pass"
                        errInfo:
                          type: string
                          example: ""
                        errInfoZh:
                          type: string
                          example: ""
                        bandWidth:
                          type: number
                          example: 195.11
                  testScene:
                    type: string
                    example: "singleNode"
                  status:
                    type: string
                    example: "running"
                  testNodeNum:
                    type: number
                    example: 1
                  testRdmaNum:
                    type: number
                    example: 8
                  bandWidthThreshold:
                    type: number
                    example: 0
